package form

const FORM_FIELD_TYPE_BLOCKEDITOR = "blockeditor"
const FORM_FIELD_TYPE_CHECKBOX = "checkbox"
const FORM_FIELD_TYPE_COLOR = "color"
const FORM_FIELD_TYPE_DATE = "date"
const FORM_FIELD_TYPE_DATETIME = "datetime"
const FORM_FIELD_TYPE_IMAGE = "image"
const FORM_FIELD_TYPE_HTMLAREA = "htmlarea"
const FORM_FIELD_TYPE_EMAIL = "email"
const FORM_FIELD_TYPE_FILE = "file"
const FORM_FIELD_TYPE_HIDDEN = "hidden"
const FORM_FIELD_TYPE_NUMBER = "number"
const FORM_FIELD_TYPE_PASSWORD = "password"
const FORM_FIELD_TYPE_RADIO = "radio"
const FORM_FIELD_TYPE_SELECT = "select"
const FORM_FIELD_TYPE_STRING = "string"
const FORM_FIELD_TYPE_TABLE = "table"
const formFieldTypeRepeater = "repeater"
const FORM_FIELD_TYPE_TEL = "tel"
const FORM_FIELD_TYPE_TEXTAREA = "textarea"
const FORM_FIELD_TYPE_URL = "url"
const FORM_FIELD_TYPE_RAW = "raw"
